extends: airbnb-base

parser: babel-eslint

plugins:
  - babel
  - json

env:
  browser: true
  node: true
  es6: true

rules:
  no-console: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-underscore-dangle: 'off'

overrides:
  - files:
      - "config/**"
      - "devtools/**"
      - "**/webpack.config*.js"
      - "**/.babelrc*"
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true

  - files:
      - src/**/*
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
      no-console: error
